project_name: 'OCR'
experiment_name: 'exp1'
num_classes: 24
n_epochs: 30
accelerator: 'gpu'
device: 0
monitor_metric: 'valid.StringMatch'
monitor_mode: 'max'

model_kwargs:
  backbone_name: 'resnet50'
  pretrained: true
  cnn_output_size: 512
  rnn_features_num: 48
  rnn_hidden_size: 64
  rnn_dropout: 0.1
  rnn_bidirectional: true
  rnn_num_layers: 2
  num_classes: 11

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 1e-3
  weight_decay: 1e-5

scheduler: 'torch.optim.lr_scheduler.ReduceLROnPlateau'
scheduler_kwargs:
  mode: 'min'
  factor: 0.5
  patience: 20
  min_lr: 1e-5

losses:
  - name: 'ctc'
    weight: 1.0
    loss_fn: 'torch.nn.CTCLoss'
    loss_kwargs: {}

data_config:
  batch_size: 48
  num_iterations: 100
  n_workers: 4
  width: 416
  height: 96
  vocab: '0123456789'
  text_size: 13